### ISSUE TITLE
Deprecate c.js

### ISSUE THREAD

**Issue by jbucaran** [jbucaran/clor#12]
I wrote c.js because I wanted to explore template literals, but now I regret having incorporated this functionality into this project. I think c.js would make a little nice side project, but it's place is not in clor.

**Comment by abhisekp** [comment]
Why would you regret having c.js functionality? It works fine and great.

**Comment by jbucaran** [comment]
@abhisekp I've been wanting to revive <samp>c`...`</samp> as a separate module, but haven't found the time.

> It works fine and great.

Thanks! :) But IMO it's out of the scope of clor .
