### ISSUE TITLE
Browser support.

### ISSUE THREAD

**Issue by DylanPiercey** [jbucaran/clor#7]
The implementation would be very different (ie: %c style syntax) but it would be cool to have an isomorphic api for colors in javascript consoles.

**Comment by bucaran** [comment]
@DylanPiercey Hey.

Cool! How would that work exactly? is this something you'd like to contribute or just would like see implemented at some point?

**Comment by DylanPiercey** [comment]
@bucaran I'm going to give it a whirl since this lib is easy to grok. Basically It would involve making a completely separate implementation that targets the browser using the "browser" field of the `package.json`. If you are not familiar with styling the browser terminal you can check out https://developer.mozilla.org/en/docs/Web/API/console#Styling_console_output. Sadly it's very different from the node api.

**Comment by DylanPiercey** [comment]
After looking at it a bit basically it would involve rewriting https://github.com/chalk/ansi-styles/blob/master/index.js to work in the browser which may require more work than I had thought, especially since not everything translates perfectly.

**Comment by bucaran** [comment]
> https://developer.mozilla.org/en/docs/Web/API/console#Styling_console_output

Thanks!

> After looking at it a bit basically it would involve rewriting https://github.com/chalk/ansi-styles/blob/master/index.js to work in the browser which may require more work than I had thought, especially since not everything translates perfectly.

TBH I'd like to ditch that dependency and rewrite everything into clor.

**Comment by DylanPiercey** [comment]
@bucaran one other annoying, but important, difference is that in the browser terminal you must pass in `n` arguments for each `%c` directive, ie each new style. The only real way to abstract this away and keep the api consistent (if you were to attempt this) is to use the `#log` method. Using the native console.log would be impossible to keep symmetrical.

**Comment by bucaran** [comment]
Thanks!

> You can use the "%c" directive to apply a CSS style to console output:

What does `c` stand for?

The browser console API does seem quite different to node's.

**Comment by DylanPiercey** [comment]
@bucaran I presume the %c is for css. Each %c will wrap the following text in a <style>.

**Comment by bucaran** [comment]
Got it. Ah, the never ending computer science problem of adding color to stuff... :)

**Comment by bucaran** [comment]
@DylanPiercey I was going over the code (it's been a while since I last touched this), and remembered you can:

```js
clor.red.bold("hi").log(function (args) {
  process.stdout.write("[" + timestamp() + "] " + this)
}/*, ... */)
```

Could this work? Like you could create your own log function like that.

**Comment by DylanPiercey** [comment]
@bucaran I think you could make it work like that but you would be parsing the ANSI style colors to %c which would mean that the browser would have to have both implementations bundle in it. Size might not matter though since this module would like be used for debugging type code.

**Comment by jbucaran** [comment]
@DylanPiercey Have you come up with a solution since we last discussed it here?

> I have been looking for a nice isomorphic/universal way to style the console for some time, 

I think this can be accomplished now that clor exposes a `c` tagged template literals function.

See: https://github.com/jbucaran/clor#tagged-literals

**Comment by DylanPiercey** [comment]
@jbucaran so far my solution has only been to duplicate the logs and use `process.browser`. (Sorry for the late reply, I missed this).

**Comment by jbucaran** [comment]
@DylanPiercey Great. Anything you could share? 🤔

**Comment by DylanPiercey** [comment]
@jbucaran one thing I was thinking was changing the return for the tagged template literal to be an array.

This way it could be used isomorphically like so:

```js
console.log(...c`<red>${greeting}</red>`)
```

I get that it's not perfect but at least this way the API would be the same in both browser and server.

What are your thoughts?

**Comment by jbucaran** [comment]
@DylanPiercey Might be worth a try. Can you put a PR together?

**Comment by jbucaran** [comment]
I've removed the `c` literal to simplify long term maintenance.

See #12.

👋
