### ISSUE TITLE
determine is terminal supports color

### ISSUE THREAD

**Issue by lukeed** [jbucaran/clor#9]
Needs [`supports-color`](https://www.npmjs.com/package/supports-color)

**Comment by jbucaran** [comment]
@lukeed I'll fix something and cut a new release soon. `supports-color` does a lot of stuff, some of which seems even more ludicrous than IE6 support, so I will not include that dependency, but I will do the most sensible checks like stdout.isTTY and check for $TERM.

**Comment by lukeed** [comment]
Sounds good, thanks!

**Comment by jbucaran** [comment]
Fixed in 5.0.0.

**Comment by lukeed** [comment]
Thanks 😀
